---
name: Create release PR

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to release
        required: true
        type: choice
        options:
          - kadmin
      version:
        description: Version to release
        required: true
        type: string

env:
  DEBIAN_FRONTEND: noninteractive
  CARGO_INCREMENTAL: "false"

jobs:
  release-pr:
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: chainguard-dev/actions/setup-gitsign@4d37df0d85a91f619edc34a8803323033cdcb124 # main
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      - uses: taiki-e/install-action@43aecc8d72668fbcfe75c31400bc4f890f1c5853 # v2.83.2
        with:
          tool: just,cargo-release,cargo-workspaces
      - run: just ci-build-deps
      - uses: cargo-bins/release-pr@0c019c0e5a6b9f722578d231d43ba900cacc5ffa # v2.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          crate-name: ${{ inputs.package }}
          pr-label: release
